server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/awm
    username: awm
    password: awm123

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.awm: DEBUG
